### ISSUE TITLE
Decide whether to scrap the websocket code and start again, or refactor

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/websocket#1]
So it's no secret the websocket-server.js file is complete and utter trash when it comes to maintainability and readability.

It either needs completely nuking and starting again, or refactored into modules. I would prefer the latter as get the project working again then refactor later.

Thoughts?

**Comment by microwavekonijn** [comment]
I think it would be a good idea to extract all the methods to their own files regardless what approach is being taken and add some comments describing what each is for. I tried to look through it, but I have no idea what is used by what and when or at least it is very difficult.

**Comment by Maelstromeous** [comment]
Ha yeah... it's a mess. Basically there's a main "thread" which basically just calls a whole load of functions. It's **heavily** callback function dependant, which results in a ton of callbacks of callbacks of callbacks. It's a bit crazy and I often lost my sanity creating it.

It also had a lot of database query leaks, where it wouldn't release connections correctly. I fixed this a bit by wrapping all DB calls in a function, so it shouldn't leak any more.

I did say it was horrible :P

**Comment by P3RF3CTION** [comment]
I would go as well for the **Second Option** as mentioned to refactor into modules first of all.
Most important is anyways the fact to not rely on other API's then Census or the internal one of the Project, to not end up as it happened this time.

**Comment by marci4** [comment]
Yeah refactoring would be a good start.

Language should stay JS? Or can we think about e.g. TS?

**Comment by Hailot** [comment]
I would either scrap or go by a heavy refactoring..  shouldnt take to long tbh..

**Comment by Maelstromeous** [comment]
> Yeah refactoring would be a good start.
> 
> Language should stay JS? Or can we think about e.g. TS?

Typescript is certainly an option, don't see why we couldn't use it. I've not used it myself but it looks pretty similar tbh

**Comment by Hailot** [comment]
TS is essential JS..  its just makes you be more strict about your data.. which is a good thing

**Comment by microwavekonijn** [comment]
Specially when you work with multiple people it is nice to have. Plus you get type hinting, and reflection.

![](https://i.kym-cdn.com/photos/images/newsfeed/000/591/928/94f.png)

**Comment by Hailot** [comment]
yes..  but could achieve that with straight nodejs aswell.. using sequilze.. ive got some code for that i can show you, i am using for a psb tracker

**Comment by microwavekonijn** [comment]
I know, typescript just does it better.

**Comment by Hailot** [comment]
hint hint.. typescript + sequlize is what we want ;)

**Comment by Maelstromeous** [comment]
Ok guys so we seem to have a majority to refactor the project rather than a full re-write, which is also my preference, and I don't see any major objections to this, so I'm closing this issue down and creating a new one with the objective of re-factoring.
