### ISSUE TITLE
ContainerModules are not executing "terminating" upon process termination

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/websocket#103]
We need to investigate and test why this isn't occuring. Since we're using CI/CD methodologies and the fact the containers are meant to be treated like cattle, we need to make sure these calls are working.

**Comment by microwavekonijn** [comment]
I just looked at the Kernel, and the termination code is missing(i.e. calling the terminate methods on services).
To do:
- [ ] Readd termination code to terminate.
- [ ] Unhandled rejection should also be terminate the app.
