### ISSUE TITLE
Instance Winner calculations

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/websocket#125]
We need to actually be able to calculate who wins alerts and be able, on a per instance type basis (MetagameEvent, Custom Types) to calculate the winner.

Propose we add a `calculateWinCondition` method to the instance interface which will go off and calculate the winner of that instance type. Therefore this will enable custom win types to be defined.

Hardest part is figuring out the triggers. In metagame event we can do this simply by checking at the end instance trigger, which may be appropriate for most types but some e.g first to X kills won't work like that.

Blocks #37

**Comment by Maelstromeous** [comment]
@microwavekonijn do you believe we can trust the metagameevent end message which contains the `faction_vs` territory %s? I had a distinct feeling that it won't be satisfactory.

**Comment by microwavekonijn** [comment]
Don't think so, I believe I saw events come through that couldn't represent the final state of the continent.

**Comment by Maelstromeous** [comment]
In that case we will need to pull in the entire map upon event start and update it as we go. We will need a robust method of calculating the territory %s based off the map result.

- [ ] Pull in initial map state from Census and dump
- [ ] Create function to scan the map state and subsequent captures and calculate
- [ ] Add trigger to calculate map state at the metagame end message
- [ ] Add `winner` property to `instance_metagame` and fill with the result.

**Comment by Maelstromeous** [comment]
Note, we cannot trust taking a snapshot of the zone state as the alert ends due to a race condition where the metagame event message may appear later after a few facilities have flipped to the victor. Nor can we take a snapshot of the map seconds before the alert ends, as I have known some bases to be taken literally last second to swing the result.

**Comment by Maelstromeous** [comment]
So a complication has arose concerning cutoffs, therefore taking a snapshot (or deriving the map's last state) is simply not enough as we require knowledge of what bases are cut off and not contributing to territory percentages.

Thinking about how to handle this, I've come up with the following theory, based very roughly from [Graph Theory](https://en.wikipedia.org/wiki/Graph_theory):

1. Pull in the zone lattice lane data from Census e.g https://census.daybreakgames.com/get/ps2/facility_link?zone_id=8&c:limit=1000
2. Starting at each factions warpgate (calculated via [census filtered by facility type 7](http://census.daybreakgames.com/get/ps2:v2/zone/?zone_id=2&c:join=map_region^list:1^inject_at:regions^hide:zone_id^terms:facility_type_id=7)), we check each facility for the same faction's ownership.
3. If the faction owns the base, record it and then continue to traverse that base's links recursively until we have no more bases / links to scan.
4. Once all links have expired, move onto the next faction.
5. Once the 3rd faction's links have expired, we should therefore have a full view of the map, excluding cut off territory.

Therefore, we only have knowledge of the bases connected to the warpgate, which is how the base calculates territory percentage calculations, cutoff bases are not counted. Bases which are connected to each other, but are still cut off from the warpgate are also continued not to be counted.

**Comment by Maelstromeous** [comment]
## Implementation

Scenario: Scan Esamir map state

Prereqs:
* We put this in a new class, cos bugger doing this in a single function in `EndAction` plus it could be used by other instance types.
* We create a function called `traverse` which accepts the arguments `facilityId` and `faction`.
* We create a data object in the class which holds the facilityId and faction.

### Execution:

Main thread:

1. Get facility ID for one of Esamir's warpgates, say South West (`259000`)
2. Call the `traverse()` method supplying facility ID and the current faction owner.

### Traversal 
1. Pull in the associated links for the facility from the lattice link data (note, links may be A or B)
  * From this data using the warpgate as an example, we now know that SW warpgate is linked to facilities:
    * `241000` Everett Supply Co, 
    * `244300` Frostbite Harbour,
    * `244600` Two Stone Beach
2. In the function, we perform two checks:
  * Has the base already been scanned?
  * Is the base not the owner of the previous base?
3. If either of the above compute, we return false as the base is an enemy one, or has already been collected.
4. If case 2 is false, we create a promise per facility link. This then calls the `traverse` method with the current base's faction and facility ID.
5. We invoke the promise.
6. If all of the results of the promise is false, we fulfil the promise, which has been called from at the very source, the warpgate.
7. Once all of the promises have been fulfilled, we now know the fully connected links to the warpgate in question. 

### Collation

We then return the entire class with the results, as either raw base count or percentages.
