### ISSUE TITLE
CharacterPresence expiry calculations are wonky and causing high database traffic

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/websocket#137]
Currently now the staging socket has been running a while, we have 31k character presence records. I wish that many people were playing the game at one time.

This is causing a practical infinate loop of constant creations and deletions, spiking CPU traffic and creating write queues (which is a bad thing mkay). Logic needs further investigation.

**Comment by microwavekonijn** [comment]
I would use the Redis Set type and make it into something called active or participating characters. Make a set for every interval push to that set all character id's, and after the interval is done create a new set and use the old set to count the items after which you delete it. Much simpler system and much less guess work.

**Comment by Maelstromeous** [comment]
Will hopefully be fixed by #148
