### ISSUE TITLE
NASTY! Ending alerts only works ONCE!!!

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/websocket#139]
Good job I've been testing this with a fine toothcomb... it appears that via the websocket we can end an alert manually once, but then can't end it again. The function is run, but it's like the query never actually completes.

Need to diagnose the logic exactly. Restarting the socket results in the same instance ending if requested again, but it will only update one, it refuses to update / end others until rebooted.

```typescript
// InstanceHandler.endInstance()
       try {
            // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
            const res = await this.instanceMetagameModelFactory.model.updateOne(
                {instanceId: instance.instanceId},
                {
                    state: Ps2alertsEventState.ENDED,
                    timeEnded: new Date(),
                },
            );

// SECOND RUN DOESN'T GET PAST HERE

            console.log(res.nModified);

            // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
            if (!res.nModified) {
                InstanceHandler.logger.error(`No instances were modified on end message! ${instance.instanceId}`);
                return false;
            }

            remove(this.currentInstances, (i) => {
                return i.instanceId === instance.instanceId;
            });

            InstanceHandler.logger.info(`================ SUCCESSFULLY ENDED INSTANCE "${instance.instanceId}" ================`);
            this.printActives();
            return true;
        } catch (err) {
            // eslint-disable-next-line @typescript-eslint/restrict-template-expressions
            throw new ApplicationException(`Unable to end instance "${instance.instanceId}"! ${err}`, 'InstanceHandler');
        }

**Comment by microwavekonijn** [comment]
Have you tried running the query directly?

**Comment by Maelstromeous** [comment]
Not yet, although I shouldn't expect that to fail? Not sure why it would, it seems like it's getting stuck on the last query it performs on that collection. I tested by adding an alert, then it wouldn't subsequently end it until restart. It's like the collection is locked.

**Comment by microwavekonijn** [comment]
I don't know, but running it directly gives you more control and might eliminate hard to see mistakes.

**Comment by Maelstromeous** [comment]
Put DB in debug mode and the query is being sent.. and it god damn works now... WAT

**Comment by Maelstromeous** [comment]
This has mysterously fixed... closing.
