### ISSUE TITLE
Integrate database layer and @Hailot 's models into Typescript

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/websocket#19]
Spinoff from #16 ,

We need to migrate the database models @Hailot has made into Typescript and integrate Sequlize.

**Comment by Maelstromeous** [comment]
@Hailot could use a hand with this one, time has come to store events :D

**Comment by marci4** [comment]
We need a new framework as result of #42

**Comment by Maelstromeous** [comment]
Closing, making new issue.
