### ISSUE TITLE
Decide on http request package

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/websocket#27]
We need to decide the websocket's http request package for requests to Census / PS2Alerts API etc.

> Yes, I know. I would like to directly pull them from the API, but first we need to decide on a http request package

_Originally posted by @marci4 in https://github.com/ps2alerts/websocket/pull/23_

**Comment by microwavekonijn** [comment]
As this is a node application, just the node http module might be enough. I mentioned node-fetch for ps2census as I want to create browser compatibility(same code for browsers and node).

**Comment by Maelstromeous** [comment]
Does it support https out of the box @microwavekonijn ?

**Comment by Maelstromeous** [comment]
Also the package does need to use http status codes, if we get a 5xx we need to re-try eventually.

**Comment by microwavekonijn** [comment]
Didn't think about that. Still I want to push ps2census v0.1.3 next Wednesday, which will also include the endpoints.

Census API doesn't use status codes, you will have to use a timeout or read the json object to see if something is wrong.

**Comment by Maelstromeous** [comment]
@microwavekonijn sorry I think there's a slight misunderstanding when it comes to status codes. If the server is 100% dead (which we know it has been lately) it will emit a 500. As you say, Census isn't smart enough to denote "nothing found" as a 404, but it still will emit a 500 in a total FUBAR scenario.

**Comment by Maelstromeous** [comment]
And also we need to have a timeout mechanism, we should reasonably expect Census to respond in 15 seconds, configurable depending on query / resolutions we have to do.

**Comment by microwavekonijn** [comment]
I didn't get a 500 code when the api was down a few days ago. I tried with postman, first I got service is not available wrapped inside a json object, and later empty responses(all 200 codes).

**Comment by Maelstromeous** [comment]
Oh wait it just returns nothing doesn't it... fuck sakes :roll_eyes:

**Comment by Maelstromeous** [comment]
Regardless, we may be making calls to our own API, which will use proper status codes, so we kinda need it to be supported anyway.

**Comment by microwavekonijn** [comment]
Yeah, my idea was to write some functions that are able to make the calls and also catch empty responses/service not available and throw exceptions when that happens.

**Comment by vostrnad** [comment]
Thanks to request, the de facto http request package for Node.js being [deprecated](https://github.com/request/request/issues/3142), there is now a [list of good alternatives](https://github.com/request/request/issues/3143). Definitely worth checking out.

**Comment by Maelstromeous** [comment]
@vostrnad good spot. Looks like bent might be the most useful: https://github.com/mikeal/bent

**Comment by microwavekonijn** [comment]
That was what I was looking for. The alternative to axios is got.

**Comment by microwavekonijn** [comment]
Lol, how did I miss this. https://nodejs.org/api/https.html#https_https_get_url_options_callback

**Comment by vostrnad** [comment]
HTTP request packages exist for a reason. The native http module is cumbersome, which is why people usually use an easy-to-use and well-maintained wrapper around it.

**Comment by microwavekonijn** [comment]
Yeah, but the census API is kind of an exception. As I said they don't use http status codes and only use get methods. In either case to handle the API properly we need to write our own code to handle the requests, so then it makes sense to go with the native one for some extra performance.

**Comment by Maelstromeous** [comment]
Yeah we should use as simple as possible package, no need to bring in bloat when we don't require it.

**Comment by Hailot** [comment]
i would say lets go with axios ..  imo the best client out there for this

**Comment by Maelstromeous** [comment]
Seems we have achieved consensus. Axios it is.
