### ISSUE TITLE
Create EditorConfig

### ISSUE THREAD

**Issue by marci4** [ps2alerts/websocket#29]
We should have a editor config which should help the IDE follow the code guidelines in this project.

Attached you can find my config for now.
[.editorconfig.txt](https://github.com/ps2alerts/websocket/files/4875493/default.editorconfig.txt)

**Comment by Maelstromeous** [comment]
Is this an IntelliJ config?

**Comment by marci4** [comment]
Webstorm config exported as "EditorConfig file"

**Comment by Maelstromeous** [comment]
I don't think we should be tied to a particular editor. Feel free to add it to the .gitignore as a PR to the revive repo and then you're free to use it :)

**Comment by marci4** [comment]
I think you can use the EditorConfig in Visual Code as well.
It would help with stuff like "spaces in the input brackets" etc

**Comment by Maelstromeous** [comment]
Think the vast amount of rules ESLint has introduced from #33 will handle this somewhat :)
