### ISSUE TITLE
Remove 3rd party API integration

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/websocket#3]
The websocket is heavily dependent on Jhett12321's middleman API. Unfortunately that project is no longer being maintained. Code referencing the project needs removing and a common interface creating.

**Comment by Hailot** [comment]
We just hoop it up to the census websocket.. 
andf use the query api to get all the other data you also got withb jett.. thats the small problems :P

**Comment by Maelstromeous** [comment]
Yep, there's two units of work though, making it listen and subscribe to census steaming (#4 ) but also getting that extra data we need, which needs to be manual API calls (#5 )
