### ISSUE TITLE
Agree on eslint rules

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/websocket#30]
Let's formulate a list of ESLint rules so we don't need to worry about it in PRs.

My personal suggestions other than what's already in:

- EOF new line
- New Lines after control structures (ifs, fors, eachs, switches etc)
- New Lines after functions & constructs
- New LInes after sets of properies (e.g. before construct)

**Comment by vostrnad** [comment]
I suggest everyone (who wants) leaves a comment with their preferred style/syntax rules (no need to mention rules that have already been mentioned, unless you'd prefer to have them the other way around). After that I can compile an ESLint configuration from these suggestions, add other rules that I believe are sensible and submit a PR.

**Comment by Maelstromeous** [comment]
@vostrnad feel free to submit the rules you feel should be added then we can have a discussion around it

**Comment by vostrnad** [comment]
My personal suggestions:
- one true brace style:
```typescript
if (a) {
    ...
} else {
    ...
}
```
- consistent indents, I'd go with the default 4 spaces
- trailing commas
- semicolons
- enforce `import` syntax over `require`
- prefer `===` and `!==` over `==` and `!=`
- enforce max one class per file
- consistent class member ordering, something along these lines:
```json
[
    "public-static-field",
    "public-instance-field",
    "private-static-field",
    "private-instance-field",
    "constructor",
    "public-static-method",
    "public-instance-method",
    "private-static-method",
    "private-instance-method",
]
```
- enforce `readonly` for unchanged class member, same as `const` is preferred for unchanged variables
- for array types prefer `[]` over `Array` with simple types, but `Array` for complex types:
```typescript
type A = number[];
type B = SomeType[];
type C = Array<Set<number>>;
```
- consistent bracket and curly spacing, not sure which way though:
```typescript
[1, 2, 3, 4]
{name: 'John'}
```
or
```typescript
[ 1, 2, 3, 4 ]
{ name: 'John' }
```
I have more rules in mind that I want to add, but these are the only ones I think someone could disagree with.
