### ISSUE TITLE
Create background task / service to prune online players if not seen in a threshold time

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/websocket#31]
Need a background task to prune the online players for the PS2 worlds. We also need to update handlers to keep this information fresh as possible, using a "last seen" unix timestamp. The task will run through the online players and check their last online times, and if it's over a certain threshhold (currently thinking 10 mins) remove them from being online.

_Originally posted by @Maelstromeous in https://github.com/ps2alerts/websocket/pull/23/review_comment/create_

**Comment by microwavekonijn** [comment]
https://github.com/ps2alerts/websocket/pull/23/files/8f267be18568e940d235e2a2b31728cd0c1ebf2a#r449925169
> 
> 
> I don't think it needs to be its own service. However I would put a list like that into it's own class something like DecayingSet and use that. With some clever use of a WeakSet and a rotating array of normal Sets you can create better performance without having to iterate over all elements.
> 
> In general use Set and Map over Array and Object in these kind of cases. They have better performance as I believe it implements a heap under the hood(though don't quote me on that). Also WeakSet and WeakMap are pretty cool as they do not block the garbage collector from freeing memory.

**Comment by marci4** [comment]
PlayerHandler contains a method to update the lastseen of a player.

**Comment by Maelstromeous** [comment]
Thinking of iterating a map of players and check their last seen values, if it's higher than threshold, delete that entry.
