### ISSUE TITLE
Update ps2census to latest version (0.2.4)

### ISSUE THREAD

**Issue by marci4** [ps2alerts/websocket#36]
The following things have to be fixed, when we update to the latest ps2census version (current version is 0.1.2):

- [x] CensusProxy.ts --> enable 'ContinentUnlock'
- [x] ContinentUnlockEvent.ts --> Remove event as unknown cast
- [x] Swap from GenericEvent to PS2Event

**Comment by Maelstromeous** [comment]
We will also need to use the types that @microwavekonijn said he'd expose via the package, rather than calling the package's files directly (which is incredibly naughty thing for me to do)
