### ISSUE TITLE
Settle on Database Engine

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/websocket#42]
We are now ready to store some data thanks to @marci4's contributions to the handlers. The big question now is the following:

## SQL or NoSQL?

If SQL, what kind? MariaDB / MySQL or Postgress? 

If NoSQL, Mongo or Key Value? Etc

**Comment by microwavekonijn** [comment]
For front-end SQL is the best option as with MariaDB you get excellent read performance(Mysql too, but it is more limited). NoSQL like mongo(document database) can be quite nice to store the data quickly(insert performance), it is flexible in terms of quickly being able to create new collections, and you are able to write these very readable aggregate queries.

When choosing mongo you can choose to put everything into there(each world their own set of collections), aggregate every few seconds which the results are then pushed to the front-end database.

**Comment by Maelstromeous** [comment]
Prompting @Hailot @marci4 @vostrnad for comments

**Comment by marci4** [comment]
Only used SQL databases, not sure what the benefits of having NoSQL are.
Not sure if we want to maintain 2 different engines and a aggregator in between.

**Comment by Maelstromeous** [comment]
So my two cents:

I like the idea that mongo provides us with flexibility, which will be very useful as the game continues to get updates. We also don't strictly need hard relationships with data, I've never had the need to cascade an update for like a player name for example.

My primary concern with any of the engines we use is update performance. Don't get me wrong guys, we'll be looking at potentially 20 updates a second during the games prime time and depending on how much data we store. We will need to benchmark the performance of not only the app but the IOP/s of the database layer and even disks.

While many people understand MySQL and would prefer it, we should use the best tool for the job. By the sounds of it, the aggregation can be achieved even via mongo, however I want to achieve aggregation via code and update queries so the code is database platform agnostic. The intent is to write the aggregators and inject a database driver, where the aggregator code has a single interface to write to, and it's the work of the driver to translate that into a SQL update or whatever mongo requires.

**Comment by NotThatBowser** [comment]
In my experience, maintainability becomes extremely important in any long-running project. Relational databases have the benefit of being extremely defined so they can be simpler to reason about, however a document-based database would let you modify the structure with less effort later on. With the game's devs looking towards new features, I can imagine various changes being required over time.

I agree that detaching the aggregation from the actual query is the way to go for either db type. As well as the general benefits of detaching logic from implementation, it could also provide a more rigid conceptual structure for a document-based db.

With that structure, I could see a document-based system being more beneficial for ongoing maintenance as you can benefit from its flexibility while retaining clear pathways for adding/updating business logic.

That said, I have minimal experience with databases at this scale, both in scope and potential throughput so I can't comment on potential performance. However, I understand that it's somewhat easier to scale document-based databases horizontally.

**Comment by Maelstromeous** [comment]
Thanks for your input @NotThatBowser and for first collaboration 👍

**Comment by Maelstromeous** [comment]
Ok guys, going to bite the bullet here and say we go with Mongo. The flexibility it affords us is quite key, handling database migrations across environments isn't a massive factor and the language of the project is kept much simpler as each object is stored in JSON, written in JSON and accessed like you would in JSON.

I don't believe the project would benefit from having two database engines running, there's a massive maintainability factor here so we're going to stick with one.

We also don't really benefit from having strict relationships, nosql can still provide them, but we don't require cascading updates for example.

Once we've written the aggregates, we can read off said aggregates and gain a lot of read processing power savings as a result.

**Comment by Maelstromeous** [comment]
Feel free to reopen if anyone else has further to add.
