### ISSUE TITLE
Create ability to query census for additional information the middleman API provided

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/websocket#5]
The nice thing about the middleman API was that it gave us various bits of info, like the outfit name rather than just ID, facility names, etc. It also offloaded caching as well.

We will need to replicate this system, whether it be a separate application to solely handle these requests (the website may need to make use of it as well) or built into the websocket as a module.

It needs to be doing the following:
- Accepting a service ID and producing an interface to query census for information
- Caching the results, with a TTL of 24 hours. This could be done in Redis, but considering the volume of data we may be caching may have to do it in the database. Bear in mind, our infrastructure is memory limited.

**Comment by Maelstromeous** [comment]
@microwavekonijn is going to add this functionality into his PS2Census Client library, where we can run methods which will do Census queries under the hood in order for us to determine such information like "was this death a suicide" etc which isn't available from the websocket stream directly.

**Comment by Maelstromeous** [comment]
@microwavekonijn is census package ready for this?

**Comment by microwavekonijn** [comment]
There is functionality to query the api, but it is not tied to the client yet. It is being worked on.

**Comment by Maelstromeous** [comment]
@microwavekonijn has implemented this functionality which we can now use. Good work!
