### ISSUE TITLE
CensusStreamService is regarded as "started" but not actually connected

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/websocket#52]
We currently have a race condition where the Kernel has regarded the app as fully started when actually Census is still connecting.

We need to add a promise of some sort to prevent the kernel marking the CensusStreamService as connected when we haven't yet received the `ready` event.

**Comment by microwavekonijn** [comment]
Is this based on the logs? I think the service is started correctly. I think the problem lies with that the listeners are registered after the client has connected. Basically the promise returned from the watch method on client is resolved at the same moment as the ready event is emitted.

**Comment by Hailot** [comment]
What Branch is it on ? revive or feature#48 ? or is it with both.. then i can go trough it aswell

**Comment by microwavekonijn** [comment]
Revive I would say.

**Comment by Maelstromeous** [comment]
@microwavekonijn noooot quite there yet, needs to do it after successfully subscribed. Sorry, I forgot about that bit.

**Comment by Maelstromeous** [comment]
@Hailot @microwavekonijn this is based on the `revive` branch. Think the started method just needs to finish when the ready event is received.

**Comment by Maelstromeous** [comment]
@microwavekonijn fancy giving this another crack?

**Comment by microwavekonijn** [comment]
Sure, but it has kind of a low priority atm for me. Mostly because it doesn't interfere with other part of the app(except that it might not receive event immediatly).

Priority atm is fixing the type guards in ps2census on the Rest commands as they are not working as expected. After that I want to crack on with the managers so the event data can be enriched with rest data.

**Comment by Maelstromeous** [comment]
Closing, not really much of an issue if we're waiting half a second for census to connect.
