### ISSUE TITLE
Create models for all events recieved trough census websocket

### ISSUE THREAD

**Issue by Hailot** [ps2alerts/websocket#6]

**Comment by marci4** [comment]
@Hailot do you have a SQL scheme ready?

**Comment by Hailot** [comment]
Well..  the scheme for the events are in the models if you check the code.,  if thats what you mean

**Comment by marci4** [comment]
@Hailot I realized this after I asked the quesiton. My bad

**Comment by Hailot** [comment]
No worries :), all the other data i would place in the api as i Think i explained over on that project, not sure though

**Comment by marci4** [comment]
Sounds good, currently working on a bit of structure and looking up the outfit_id for a character_id (including caching)

Home it is fine that I am working on your branch

**Comment by Hailot** [comment]
Are you doing that on this project ??  Cause something like that is exactly what i would put in the api project instead

**Comment by marci4** [comment]
We need this information at the time of insertion into the database?

Otherwise old alerts will not correctly display the outfits participation

**Comment by Hailot** [comment]
Well no ?  What we insert in the db is just the id of the outfit, which is what we recieve here..  there Will be enough stress loggin all the events fired from ws to the database..  those lookups Will just create bottlenecks and arent really used for anything constantly..

**Comment by marci4** [comment]
But you dont receive any outfit id e.g. for a death? Or a vehicle kill?

**Comment by Hailot** [comment]
But what would you need the outfit id for then ??

**Comment by Hailot** [comment]
I mean..  if its for actual alert calculations..  i Think i would still put that over in the api..  and keep the websocket strictly for handling the data that comes from census ws..  then keep query api data, and calculations on the api, ( maybe fired trough triggers or something )

**Comment by marci4** [comment]
Being able to display top 100 outfits for kill stats etc. Take a look at "PS2Alerts Literature" and "What data to collect"

if you want to do this correctly for past alerts, you have to store the outfit_id at the time of the alert. 

We can do this with a background job, but then we need some kind of backlog. BUt then we can move everything into this background job to not touch the database entry twice

**Comment by Maelstromeous** [comment]
A lot of this is already in the revive branch (#16), further work is required to add aggregator models etc.

**Comment by Maelstromeous** [comment]
This is now effectively done.
