### ISSUE TITLE
Integrate updates to upstream Census library (v0.3.6)

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/websocket#63]
Need to update the census library and make any changes required for integration

**Comment by marci4** [comment]
Anything specific?

**Comment by microwavekonijn** [comment]
https://github.com/microwavekonijn/ps2census/releases

Most of the changes are in v0.3.1. Client now uses the classes as types instead of the index types, there are some extra computed values, and some values are parsed now(timestamp, booleans).
